# Generated by Django 5.1.5 on 2025-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisnesuser',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
