# Generated by Django 5.1.5 on 2025-03-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('format', models.CharField(choices=[('Paperback', 'Paperback'), ('Ebook', 'Ebook')], max_length=15)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('link_to_ebook', models.URLField(blank=True)),
                ('link_to_download', models.URLField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_comment', to='books.books')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
