# Generated by Django 5.1.5 on 2025-02-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='link_to_download',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='link_to_ebook',
            field=models.URLField(blank=True),
        ),
    ]
