# Generated by Django 5.1.5 on 2025-03-07 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published date'),
        ),
    ]
