# Generated by Django 5.1.5 on 2025-03-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_bookrating_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='books',
            name='rate_the_score',
        ),
    ]
