# Generated by Django 5.1.5 on 2025-03-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books', models.ManyToManyField(related_name='cartlisted_books', to='books.books')),
            ],
            options={
                'verbose_name': 'CartList',
                'verbose_name_plural': 'CartLists',
            },
        ),
    ]
