# Generated by Django 5.1.5 on 2025-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='reservation',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
