services:
  # PostgreSQL service
  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: psycology
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  # Django app service
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - DOCKER_ENV=True
      - DB_NAME=psycology
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5433

volumes:
  postgres_data:

