# Generated by Django 5.1.5 on 2025-03-17 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published date')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(choices=[('Paula Serrano – Terapeuta Ocupacional', 'Paula Serrano – Terapeuta Ocupacional'), ('Paula Serrano – Mestre em Terapia Ocupacional, especialização em Integração Sensorial', 'Paula Serrano – Mestre em Terapia Ocupacional, especialização em Integração Sensorial')], default='Paula Serrano – Terapeuta Ocupacional', max_length=255)),
                ('duration', models.IntegerField()),
                ('recipient', models.CharField(default='Terapeutas ocupacionais com formação pós graduada em Integração Sensorial', editable=False, max_length=100)),
                ('objectives', models.TextField()),
                ('methodology', models.CharField(default='As sessões de trabalho serão on line, teóricas e com analise de vídeos de casos clínicos.', editable=False, max_length=255)),
                ('content', models.TextField()),
                ('fmw', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='img/courses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
